import { Poppins } from 'next/font/google'
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import './globals.css'

const poppins = Poppins({ weight: ['400', '300','600'],
subsets: ['latin'], })

export const metadata = {
  title: 'CWD Solutions',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <Navbar />
{children}
<Footer />
</body>
    </html>
  )
}
